import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomeComponent from '../component/Home'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Md Borhan Uddin Personal Blog</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeComponent />

    </div>
  )
}
